# Generated by Django 5.2.17 on 2026-08-31 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('CRITICAL', 'Đặc biệt nguy hiểm')], default='MEDIUM', max_length=20, verbose_name='Mức độ nguy cơ')),
                ('reasons', models.JSONField(default=list, verbose_name='Lý do cảnh báo')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Đã xử lý')),
                ('resolution_notes', models.TextField(blank=True, default='', verbose_name='Ghi chú xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_warnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cảnh báo học vụ',
                'verbose_name_plural': 'Danh sách Cảnh báo học vụ',
                'ordering': ['-created_at'],
            },
        ),
    ]
