# Generated by Django 5.2.17 on 2026-08-31 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaloNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('parent', 'Phụ huynh (< 25 tuổi)'), ('student', 'Học viên (≥ 25 tuổi - Tự chủ)')], max_length=20, verbose_name='Đối tượng nhận')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='Họ tên người nhận')),
                ('recipient_phone', models.CharField(max_length=30, verbose_name='Số điện thoại Zalo')),
                ('cycle', models.CharField(choices=[('daily', 'Hằng ngày'), ('weekly', 'Hằng tuần'), ('monthly', 'Hằng tháng')], default='weekly', max_length=20, verbose_name='Chu kỳ')),
                ('ai_generated_message', models.TextField(verbose_name='Tin nhắn sinh bởi AI')),
                ('status', models.CharField(default='sent', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zalo_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký Zalo AI',
                'verbose_name_plural': 'Nhật ký Gửi tin Zalo AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
