# Generated by Django 5.2.17 on 2026-09-01 08:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_zalonotificationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicwarning',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm'),
        ),
        migrations.AddField(
            model_name='zalonotificationlog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm'),
        ),
        migrations.AddField(
            model_name='zalonotificationlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='academicwarning',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='academicwarning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='zalonotificationlog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.CreateModel(
            name='StudentReminder',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily', models.BooleanField(default=True, verbose_name='Nhắc nhở hằng ngày')),
                ('weekly', models.BooleanField(default=True, verbose_name='Nhắc nhở hằng tuần')),
                ('monthly', models.BooleanField(default=True, verbose_name='Nhắc nhở hằng tháng')),
                ('preferred_time', models.CharField(default='19:00', max_length=10, verbose_name='Giờ nhận tin ưu tiên')),
                ('parent_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Họ tên phụ huynh')),
                ('parent_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Số điện thoại phụ huynh')),
                ('parent_zalo', models.CharField(blank=True, default='', max_length=30, verbose_name='Zalo phụ huynh')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Năm sinh')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cài đặt nhắc nhở',
                'verbose_name_plural': 'Danh sách Cài đặt nhắc nhở',
            },
        ),
    ]
