# Generated by Django 5.2.17 on 2026-08-31 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_code', models.CharField(db_index=True, max_length=50, verbose_name='Mã lớp học')),
                ('session_title', models.CharField(max_length=255, verbose_name='Chủ đề buổi học')),
                ('session_number', models.IntegerField(default=1, verbose_name='Buổi số')),
                ('session_date', models.DateField(verbose_name='Ngày học')),
                ('is_open', models.BooleanField(default=True, verbose_name='Đang mở điểm danh')),
                ('pin_code', models.CharField(default='1234', max_length=10, verbose_name='Mã PIN 4 số')),
                ('qr_token', models.CharField(blank=True, default='', max_length=100, verbose_name='Token QR động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ca điểm danh',
                'verbose_name_plural': 'Danh sách Ca điểm danh',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng mặt'), ('late', 'Đi muộn'), ('excused', 'Có phép')], default='present', max_length=20, verbose_name='Trạng thái')),
                ('checkin_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian check-in')),
                ('verified_location', models.CharField(blank=True, default='', max_length=100, verbose_name='Tọa độ GPS')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'verbose_name': 'Bản ghi điểm danh',
                'verbose_name_plural': 'Danh sách bản ghi điểm danh',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
