# Generated by Django 5.2.17 on 2026-09-01 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0002_course_created_at_course_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='courses.classgroup'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='pin_code',
            field=models.CharField(default='1234', max_length=10, verbose_name='Mã PIN điểm danh'),
        ),
    ]
