# Generated by Django 5.2.17 on 2026-08-31 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề bài tập')),
                ('description', models.TextField(blank=True, default='', verbose_name='Yêu cầu bài tập')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Hạn nộp bài')),
                ('is_open', models.BooleanField(default=True, verbose_name='Đang mở nộp bài')),
                ('drive_folder_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Google Drive Folder ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài tập thực hành',
                'verbose_name_plural': 'Danh sách Bài tập thực hành',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('file_url', models.URLField(max_length=500, verbose_name='Đường dẫn file nộp')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Điểm số')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='Nhận xét của giảng viên')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài nộp học viên',
                'verbose_name_plural': 'Danh sách Bài nộp',
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
