# Generated by Django 5.2.17 on 2026-08-31 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Mã chứng chỉ')),
                ('final_score', models.FloatField(default=0.0, verbose_name='Điểm tổng kết')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày cấp')),
                ('blockchain_hash', models.CharField(blank=True, max_length=128, verbose_name='Mã băm SHA-256 xác thực')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Đã thu hồi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chứng chỉ số',
                'verbose_name_plural': 'Danh sách Chứng chỉ số',
                'ordering': ['-issued_at'],
            },
        ),
    ]
