/**
 * Academic Portal Types & Data Models — TINHOCGENZ LMS
 * Enterprise Training Operations:
 * Course → Class → Learning Session → Meeting Room
 */

import { CurriculumTrack } from './auth';

export type ClassLifecycleStatus = 'draft' | 'preparing' | 'active' | 'completed' | 'closed';

export interface ClassAuditLogEntry {
  id: string;
  action: 'create' | 'edit' | 'close' | 'clone' | 'assign_teacher' | 'change_schedule';
  performedBy: string;
  timestamp: string;
  reason?: string;
  details: string;
}

export interface AcademicClass {
  id: string;
  classCode: string; // e.g. "K26-WE01"
  name: string;
  courseTitle: string;
  trackId: CurriculumTrack;
  teacherId: string;
  teacherName: string;
  currentEnrolled: number;
  maxCapacity: number;
  startDate: string; // "DD/MM/YYYY" or "YYYY-MM-DD"
  endDate: string;
  trainingDuration: string; // e.g. "12 buổi (6 tuần)"
  schedulePattern: string; // e.g. "Tối 2-4-6 (19:30 - 21:00)"
  roomName: string; // e.g. "Phòng Online 01"
  status: ClassLifecycleStatus;
  history: ClassAuditLogEntry[];
  createdAt: string;
  updatedAt: string;
}

export type MeetingRoomStatus = 'ready' | 'in_progress' | 'closed';

export interface MeetingRoom {
  id: string;
  sessionId: string;
  classCode: string;
  provider: 'google_meet' | 'teams' | 'zoom';
  meetCode: string; // Standard 3-4-3 code: "pht-mosw-wed"
  meetingUrl: string; // Full URL: "https://meet.google.com/pht-mosw-wed"
  createdBy: string;
  createdTime: string;
  status: MeetingRoomStatus;
  isAutoGenerated: boolean;
}

export interface SessionBlockchainRecord {
  hash: string;
  timestamp: number;
  sessionId: string;
  classCode: string;
  presentCount: number;
  learningResult: string;
  blockAnchorId: string;
}

export interface LearningSession {
  id: string;
  classId: string;
  classCode: string;
  sessionNumber: number;
  title: string;
  content: string; // Nội dung buổi học
  date: string; // "YYYY-MM-DD"
  startTime: string; // "19:30"
  endTime: string; // "21:00"
  teacherId: string;
  teacherName: string;
  status: 'scheduled' | 'live' | 'completed' | 'cancelled';
  meetingRoom?: MeetingRoom;
  blockchainRecord?: SessionBlockchainRecord;
}

export interface TeacherAssignment {
  id: string;
  teacherId: string;
  teacherName: string;
  teacherTitle: string;
  classId: string;
  classCode: string;
  assignedBy: string;
  assignedAt: string;
  previousTeacherName?: string;
  reason?: string;
}

export interface AcademicStudentEnrollment {
  id: string;
  studentId: string;
  studentCode: string;
  studentName: string;
  studentEmail: string;
  studentPhone: string;
  classId: string;
  classCode: string;
  status: 'active' | 'transferred' | 'withdrawn' | 'completed';
  progressPercent: number;
  attendancePercent: number;
  averageGrade: number;
  enrolledAt: string;
  transferredToClassCode?: string;
}

export type AttendanceCheckStatus = 'present' | 'absent' | 'late' | 'excused';

export interface AcademicAttendanceRecord {
  id: string;
  sessionId: string;
  studentId: string;
  studentCode: string;
  studentName: string;
  status: AttendanceCheckStatus;
  checkInTime?: string;
  reason?: string;
  verifiedMethod: 'qr_scan' | 'google_meet' | 'manual_academic' | 'teacher_check';
  blockchainHash?: string;
}

export interface AcademicNotification {
  id: string;
  title: string;
  content: string;
  type: 'class_notice' | 'schedule_change' | 'learning_reminder' | 'urgent';
  targetAudience: 'all' | 'class' | 'teachers' | 'students';
  classCode?: string;
  channels: ('email' | 'web' | 'mobile')[];
  sendReminderMinutesBefore?: number; // 30 for teacher, 5 for student
  createdAt: string;
  isSent: boolean;
  sentAt?: string;
}

export interface AcademicReportSummary {
  classes: {
    total: number;
    active: number;
    preparing: number;
    completed: number;
    averageAttendanceRate: number;
  };
  teachers: {
    totalTeaching: number;
    totalSessionsConducted: number;
    teacherStats: {
      teacherId: string;
      teacherName: string;
      sessionCount: number;
      assignedClasses: string[];
    }[];
  };
  students: {
    totalActive: number;
    highRiskAbsenceCount: number; // Vắng > 20%
    completionRate: number;
  };
}
