# Generated by Django 5.2.17 on 2026-08-31 07:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Mã tài khoản')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Địa chỉ Email')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Số điện thoại')),
                ('role', models.CharField(choices=[('student', 'Học viên'), ('teacher', 'Giảng viên'), ('academic', 'Giáo vụ học vụ'), ('admin', 'Quản trị hệ thống')], db_index=True, default='student', max_length=20, verbose_name='Vai trò')),
                ('student_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Mã học viên')),
                ('teacher_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Mã giảng viên')),
                ('class_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Mã lớp học')),
                ('school_or_class', models.CharField(blank=True, default='', max_length=255, verbose_name='Đơn vị / Lớp')),
                ('program_track', models.CharField(blank=True, default='office-fast-3in1', max_length=50, verbose_name='Chương trình đào tạo')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Bắt buộc đổi mật khẩu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kích hoạt')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Quyền truy cập admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tham gia')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Danh sách Người dùng',
                'ordering': ['-date_joined'],
            },
        ),
    ]
