# Generated by Django 5.2.17 on 2026-09-01 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Năm sinh'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Họ tên phụ huynh'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='SĐT phụ huynh'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_zalo',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Zalo phụ huynh'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật cuối'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày tham gia'),
        ),
    ]
