# Generated by Django 5.2.17 on 2026-09-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birth_year_user_is_deleted_user_parent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Học viên'), ('teacher', 'Giảng viên'), ('academic', 'Giáo vụ học vụ'), ('admin', 'Quản trị hệ thống'), ('super_admin', 'Quản trị viên cấp cao')], db_index=True, default='student', max_length=20, verbose_name='Vai trò'),
        ),
    ]
