# Generated by Django 5.2.17 on 2026-08-31 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề đề thi')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả bài thi')),
                ('duration_minutes', models.IntegerField(default=45, verbose_name='Thời gian thi (phút)')),
                ('passing_percentage', models.IntegerField(default=70, verbose_name='Điểm đạt chuẩn (%)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đang mở thi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course')),
            ],
            options={
                'verbose_name': 'Đề thi',
                'verbose_name_plural': 'Kho đề thi',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0, verbose_name='Số câu đúng')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Tổng số câu')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Tỷ lệ %')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Đạt chuẩn')),
                ('switch_tab_count', models.IntegerField(default=0, verbose_name='Số lần rời tab')),
                ('answers_draft', models.JSONField(default=dict, verbose_name='Bản nháp câu trả lời')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lượt thi học viên',
                'verbose_name_plural': 'Danh sách lượt thi',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('skill_id', models.CharField(db_index=True, max_length=100, verbose_name='Mã kỹ năng')),
                ('content', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('options', models.JSONField(default=list, verbose_name='Danh sách phương án')),
                ('correct_answer_id', models.CharField(max_length=20, verbose_name='Mã đáp án đúng')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Giải thích đáp án')),
                ('difficulty', models.CharField(choices=[('easy', 'Cơ bản'), ('medium', 'Trung bình'), ('hard', 'Nâng cao')], default='medium', max_length=20, verbose_name='Độ khó')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course')),
            ],
            options={
                'verbose_name': 'Câu hỏi khảo thí',
                'verbose_name_plural': 'Ngân hàng câu hỏi',
            },
        ),
    ]
