# Generated by Django 5.2.17 on 2026-09-01 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm'),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Bắt đầu làm bài'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nộp bài lúc'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
    ]
