# Generated by Django 5.2.17 on 2026-08-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã định danh')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Mã môn học')),
                ('title', models.CharField(max_length=255, verbose_name='Tên chương trình đào tạo')),
                ('short_desc', models.TextField(blank=True, default='', verbose_name='Mô tả ngắn')),
                ('total_sessions', models.IntegerField(default=6, verbose_name='Tổng số buổi học')),
                ('target_badge', models.CharField(default='Certiport / Bộ GD&ĐT', max_length=100, verbose_name='Chứng chỉ chuẩn đầu ra')),
                ('is_published', models.BooleanField(default=True, verbose_name='Hiển thị công khai')),
                ('order_index', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Chương trình đào tạo',
                'verbose_name_plural': 'Danh sách Chương trình đào tạo',
                'ordering': ['order_index', 'code'],
            },
        ),
    ]
