# Generated by Django 5.2.17 on 2026-09-01 08:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã lớp học')),
                ('name', models.CharField(max_length=255, verbose_name='Tên lớp học')),
                ('room', models.CharField(default='Phòng LAB 01 (Tầng 2)', max_length=150, verbose_name='Phòng học')),
                ('schedule_desc', models.CharField(default='Thứ 2-4-6 (18:30 - 20:30)', max_length=255, verbose_name='Lịch học')),
                ('max_students', models.IntegerField(default=25, verbose_name='Sĩ số tối đa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang mở lớp')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Danh sách Lớp học',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Đã xóa mềm')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm vào lớp')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.classgroup')),
            ],
            options={
                'verbose_name': 'Đăng ký lớp học',
                'verbose_name_plural': 'Danh sách Đăng ký lớp học',
                'ordering': ['-enrolled_at'],
                'unique_together': {('class_group', 'student')},
            },
        ),
    ]
